# Generated by Django 6.0.4 on 2026-05-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('register', '注册'), ('change_password', '修改密码'), ('reset_password', '重置密码'), ('analyze_single', '单条评论分析'), ('analyze_batch', '批量评论分析'), ('export_report', '导出报告'), ('upload_file', '上传文件'), ('download_file', '下载文件'), ('create_user', '创建用户'), ('update_user', '更新用户'), ('delete_user', '删除用户'), ('model_train', '模型训练'), ('model_switch', '模型切换'), ('other', '其他')], max_length=50, verbose_name='操作类型')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='操作详情')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'operation_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('task_type', models.CharField(choices=[('transformer_train', 'Transformer 训练'), ('transformer_search', 'Transformer 搜索'), ('classical_compare', '传统模型比较'), ('neural_baseline_train', '神经网络基线训练')], max_length=40)),
                ('status', models.CharField(choices=[('queued', '已排队'), ('running', '执行中'), ('succeeded', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='queued', max_length=20)),
                ('dataset_source', models.CharField(choices=[('workspace_dataset', '工作区数据集')], max_length=30)),
                ('dataset_ref', models.CharField(max_length=255)),
                ('model_family', models.CharField(blank=True, default='', max_length=40)),
                ('candidate_models', models.JSONField(blank=True, default=list)),
                ('search_type', models.CharField(blank=True, default='', max_length=20)),
                ('split_strategy', models.CharField(choices=[('pre_split', '预切分数据集'), ('auto_split', '自动 7:1:2 分层划分')], default='pre_split', max_length=20)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('metrics_snapshot', models.JSONField(blank=True, default=dict)),
                ('artifact_paths', models.JSONField(blank=True, default=dict)),
                ('log_path', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('post_run_status', models.CharField(choices=[('pending', '待处理'), ('succeeded', '成功'), ('warning', '告警'), ('failed', '失败')], default='pending', max_length=20)),
                ('post_run_message', models.TextField(blank=True, default='')),
                ('post_run_warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '训练任务',
                'verbose_name_plural': '训练任务',
                'db_table': 'training_runs',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
