# Generated by Django 6.0.4 on 2026-05-15 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='trainingrun',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['user_id'], name='operation_l_user_id_abc9ca_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['action'], name='operation_l_action_23516c_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['created_at'], name='operation_l_created_3fec78_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrun',
            index=models.Index(fields=['status'], name='training_ru_status_07d80c_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrun',
            index=models.Index(fields=['task_type'], name='training_ru_task_ty_18589c_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrun',
            index=models.Index(fields=['created_at'], name='training_ru_created_2d8451_idx'),
        ),
    ]
