# Generated by Django 6.0.4 on 2026-05-16 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('project_name', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='项目名称')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='评分')),
                ('comment_time', models.DateTimeField(blank=True, null=True, verbose_name='评论时间')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='商品/服务类别')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='数据来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['comment_time'], name='comments_comment_3ad39e_idx'), models.Index(fields=['category'], name='comments_categor_0852e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('version', models.CharField(max_length=50, verbose_name='版本号')),
                ('model_type', models.CharField(max_length=50, verbose_name='模型类型')),
                ('metrics', models.JSONField(blank=True, null=True, verbose_name='性能指标')),
                ('path', models.CharField(max_length=255, unique=True, verbose_name='模型文件路径')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否启用')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='激活时间')),
                ('is_best_candidate', models.BooleanField(default=False, verbose_name='是否最佳候选')),
                ('is_runtime_compatible', models.BooleanField(default=True, verbose_name='是否兼容运行时')),
                ('artifact_summary', models.JSONField(blank=True, null=True, verbose_name='产物摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_models', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('source_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_models', to='admin_panel.trainingrun', verbose_name='来源训练任务')),
            ],
            options={
                'verbose_name': '模型',
                'verbose_name_plural': '模型',
                'db_table': 'models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.SmallIntegerField(choices=[(1, '积极'), (0, '中性'), (-1, '消极')], verbose_name='情感类别')),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='置信度')),
                ('keywords', models.JSONField(blank=True, null=True, verbose_name='关键情感词')),
                ('analyst_note', models.TextField(blank=True, null=True, verbose_name='分析备注')),
                ('is_priority', models.BooleanField(default=False, verbose_name='是否重点关注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='analysis.comment', verbose_name='评论')),
            ],
            options={
                'verbose_name': '分析结果',
                'verbose_name_plural': '分析结果',
                'db_table': 'analysis_results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'created_at'], name='analysis_user_created'), models.Index(fields=['sentiment'], name='analysis_re_sentime_45c9f1_idx'), models.Index(fields=['created_at'], name='analysis_re_created_2bdd23_idx')],
            },
        ),
    ]
