# Generated by Django 6.0.4 on 2026-05-15 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('single', '单次分析报告'), ('batch', '批量分析报告'), ('daily', '日报'), ('weekly', '周报'), ('monthly', '月报')], max_length=20, verbose_name='报告类型')),
                ('report_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=20, verbose_name='报告格式')),
                ('status', models.CharField(choices=[('pending_enqueue', '待入队'), ('pending', '生成中'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending_enqueue', max_length=20, verbose_name='状态')),
                ('file_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='文件路径')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小 (字节)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('request_params', models.JSONField(blank=True, null=True, verbose_name='请求参数')),
                ('summary', models.JSONField(blank=True, null=True, verbose_name='报告摘要')),
                ('enqueue_attempts', models.PositiveIntegerField(default=0, verbose_name='入队尝试次数')),
                ('last_enqueue_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='最近一次入队尝试时间')),
                ('last_enqueue_error', models.TextField(blank=True, default='', verbose_name='最近一次入队错误')),
                ('processing_recovery_count', models.PositiveIntegerField(default=0, verbose_name='处理恢复次数')),
                ('last_processing_recovery_at', models.DateTimeField(blank=True, null=True, verbose_name='最近一次处理恢复时间')),
                ('last_processing_recovery_reason', models.TextField(blank=True, default='', verbose_name='最近一次处理恢复原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_token', models.CharField(blank=True, default='', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '分析报告',
                'verbose_name_plural': '分析报告',
                'db_table': 'reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='reports_status_created'), models.Index(fields=['status', 'processing_started_at'], name='reports_status_proc_start')],
            },
        ),
    ]
