# Generated by Django 6.0.4 on 2026-05-19 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='report',
            name='reports_status_proc_start',
        ),
        migrations.RemoveField(
            model_name='report',
            name='last_processing_recovery_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='last_processing_recovery_reason',
        ),
        migrations.RemoveField(
            model_name='report',
            name='processing_recovery_count',
        ),
    ]
