# Generated by Django 6.0.4 on 2026-05-15 11:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='手机号')),
                ('nickname', models.CharField(blank=True, help_text='用户昵称，用于前端显示', max_length=50, null=True, verbose_name='昵称')),
                ('role', models.CharField(choices=[('user', '普通用户'), ('analyst', '分析师'), ('admin', '管理员')], db_index=True, default='user', max_length=20, verbose_name='角色')),
                ('status', models.SmallIntegerField(choices=[(0, '禁用'), (1, '启用')], default=1, verbose_name='状态')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('code', models.CharField(max_length=128, verbose_name='验证码哈希')),
                ('purpose', models.CharField(default='register', max_length=20, verbose_name='用途')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='投递时间')),
                ('used', models.BooleanField(default=False, verbose_name='已使用')),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='失败尝试次数')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='最后尝试时间')),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
                'db_table': 'email_verification_codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'purpose', 'used'], name='evc_email_purpose_used')],
            },
        ),
    ]
